### ISSUE TITLE
join tables

### ISSUE THREAD

**Issue by melmalfa** [godot-kamma-chameleons/outcomes_tracker#10]
hi phil - the latest code michael and i are working on i just uploaded to production_cohorts_tracker (oops- i meant development! can i change that?)
we are stuck on our join table to connect locations an courses. finding the documentation very confusing. which language means we need to manually create a model and which means we don't? we do have data for it - 
the error we get is:
NameError: uninitialized constant CoursesLocation
when i try to rake db:seed

thank you!

**Comment by phlco** [comment]
Hi. What is in your seeds file that is referencing `CoursesLocation`?

What type of relationship have you set up between Courses and Locations?

**Comment by melmalfa** [comment]
it is a many to many relationship (an HABTM association), so we thought we should form a  join table between the two. so we rails migration createcourseslationsjointable.

**Comment by melmalfa** [comment]
we realize that we don't need the model files for the join table so we removed that, but seeds now giving us new error-

**Comment by melmalfa** [comment]
how do we put seeds info into this table? this isn't working: INSERT INTO courses_locations
  (course_id, location_id)
VALUES
  (1, 1),
  (2, 1),
  (3, 1),
  (1, 2);

**Comment by phlco** [comment]
If there is a `has_and_belongs_to_many` on both sides of Courses and Locations that means you'd have a pure join table between the two called `courses_locations` with `course_id` and `location_id` columns.

That table only exists in SQL. It's not expressed as an ActiveRecord model.

That means you don't access the table directly in ActiveRecord. Instead you bypass it and act on it with the ActiveRecord relations.

```
course = Course.first
course.locations  # returns all locations for that course
#=> [] 
location = Location.first
location.courses # returns all courses for that location
#=> 
```

If you wanted to set up a relationship between a course and a location you could do the following:

```
c1 = Course.create
c2 = Course.create
l1 = Location.create
l2 = Location.create
# set up the relationships by treating them as arrays.
c1.locations << l1 << l2
c2.locations = [l2]
```

**Comment by melmalfa** [comment]
thank you- michael understood your answer and fixed it.
HABTM represents many to many in an erd file, correct?

**Comment by phlco** [comment]
Correct! Closing issue. :+1:
