### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by melmalfa** [godot-kamma-chameleons/outcomes_tracker#18]
Login broken - the button doesn't respond to anything anymore - it used to-
it doesn't give any error messages, just reloads the page
it doesn't hit the login controller method select at all- a binding.pry inside the method never makes pry load-
we changed a bunch of paths and routes and names this morning- and I added another route to offer an admin search page- nested under the admins controller-
thank you!

**Comment by melmalfa** [comment]
we figured it out! forgot to close my div tag  . . . oops!

**Comment by phlco** [comment]
Good job! :+1:
