### ISSUE TITLE
Code review 

### ISSUE THREAD

**Issue by rugger403** [godot-kamma-chameleons/outcomes_tracker#46]
We moved pony gem from development to preproduction. This may be why pony worked in the console and not when deployed. If you check your gemfile we just moved it above the production phase.

Login page should have the ability to register as a new user. 

For the Cohorts page the charts should be displayed as soon as I click on a cohort.

"" for Courses 

When clicking on a student the font color is really hard to read.

**Comment by brainyandbrown** [comment]
~Thanks for moving 
```pony```

~Reasoning for restricting "new user" access discussed with DABS.

~Will change CSS color schemed for v2
